//
// Created by vka on 16.11.15.
//

#ifndef INZYNIER_SENSOR_CONFIGURATION_H
#define INZYNIER_SENSOR_CONFIGURATION_H

#define SENSOR_LONG_LENGTH      "SENSOR_LONG_LENGTH="
#define SENSOR_SHORT_LENGTH     "SENSOR_SHORT_LENGTH="
#define SENSOR_LONG_POSITION    "SENSOR_LONG_POSITION="
#define SENSOR_SHORT_POSITION   "SENSOR_SHORT_POSITION="
#define PIEZO1_POSITION         "PIEZO1_POSITION="
#define PIEZO2_POSITION         "PIEZO2_POSITION="
#define TOTAL_LENGTH            "TOTAL_LENGTH="
#define R_X_FACTOR              "R_X_FACTOR="

#endif //INZYNIER_SENSOR_CONFIGURATION_H
